/* Generated by cbindgen from crates/tpt-yaml-ffi. DO NOT EDIT BY HAND.
 * Regenerate with: cargo build -p tpt-yaml-ffi (build.rs runs cbindgen automatically). */

#ifndef TPT_YAML_H
#define TPT_YAML_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result/status code returned by every `extern "C"` function in this crate.
 *
 * `Ok` is always `0` so a caller can treat any nonzero return as failure without inspecting
 * the exact variant if they don't need to.
 */
typedef enum TptYamlErrorCode {
    /**
     * The call succeeded.
     */
    TPT_YAML_ERROR_CODE_OK = 0,
    /**
     * `tpt_yaml_parse` failed to parse the given source as YAML. See
     * [`tpt_yaml_last_error_message`] for the underlying [`tpt_yaml_core::YamlError`]'s
     * rendered message.
     */
    TPT_YAML_ERROR_CODE_PARSE_ERROR = 1,
    /**
     * A required pointer argument was null.
     */
    TPT_YAML_ERROR_CODE_NULL_POINTER = 2,
    /**
     * A byte slice argument was not valid UTF-8.
     */
    TPT_YAML_ERROR_CODE_INVALID_UTF8 = 3,
    /**
     * A node id, mapping index, or sequence index was out of bounds for the document.
     */
    TPT_YAML_ERROR_CODE_INDEX_OUT_OF_BOUNDS = 4,
    /**
     * The requested operation doesn't apply to the node's actual kind (e.g. asking for the
     * sequence length of a scalar node).
     */
    TPT_YAML_ERROR_CODE_TYPE_MISMATCH = 5,
    /**
     * A Rust panic was caught at the FFI boundary and converted into this error code rather
     * than being allowed to unwind across it (which is undefined behavior). This indicates a
     * bug in this crate or in `tpt-yaml-core` — please report it.
     */
    TPT_YAML_ERROR_CODE_PANIC_CAUGHT = 6,
} TptYamlErrorCode;

/**
 * The structural kind of a node, mirroring [`tpt_yaml_core::NodeKind`]'s variants.
 */
typedef enum TptYamlNodeKind {
    TPT_YAML_NODE_KIND_SCALAR = 0,
    TPT_YAML_NODE_KIND_MAPPING = 1,
    TPT_YAML_NODE_KIND_SEQUENCE = 2,
    TPT_YAML_NODE_KIND_ALIAS = 3,
} TptYamlNodeKind;

/**
 * The resolved type tag of a scalar node, mirroring [`tpt_yaml_core::ScalarValue`]'s variants.
 */
typedef enum TptYamlScalarType {
    TPT_YAML_SCALAR_TYPE_NULL = 0,
    TPT_YAML_SCALAR_TYPE_BOOL = 1,
    TPT_YAML_SCALAR_TYPE_INT = 2,
    TPT_YAML_SCALAR_TYPE_FLOAT = 3,
    TPT_YAML_SCALAR_TYPE_STRING = 4,
    TPT_YAML_SCALAR_TYPE_TIMESTAMP = 5,
} TptYamlScalarType;

/**
 * An opaque handle to a parsed YAML document, obtained from [`crate::tpt_yaml_parse`] and
 * released with [`crate::tpt_yaml_document_free`].
 *
 * C code must treat this as an opaque pointer — never dereference its fields, which don't
 * exist in the C header at all (`cbindgen` emits it as an incomplete `struct`). Internally it
 * just wraps a boxed [`tpt_yaml_core::Document`], the same arena the rest of the `tpt-yaml`
 * family works with.
 */
typedef struct TptYamlDocument TptYamlDocument;

/**
 * Node handles are plain `u32` arena indices ([`tpt_yaml_core::NodeId`] is a `Copy` newtype
 * around a `u32` with no lifetime or generic parameter), passed by value rather than through a
 * second heap-allocated opaque type. Convert with [`node_id_to_ffi`]/[`node_id_from_ffi`].
 */
typedef uint32_t TptYamlNodeId;

/**
 * Parse `len` bytes at `source` as a YAML document (YAML 1.2, default parser options — same as
 * [`tpt_yaml_core::parse`]).
 *
 * `source` need not be null-terminated; exactly `len` bytes are read and must be valid UTF-8.
 * `source` may be null only if `len` is `0` (an empty document).
 *
 * On success, returns a non-null document handle that the caller must eventually pass to
 * exactly one [`tpt_yaml_document_free`] call, and (if `out_error` is non-null) writes `Ok` to
 * `*out_error`.
 *
 * On failure, returns null and (if `out_error` is non-null) writes the specific
 * [`TptYamlErrorCode`] to `*out_error`; [`tpt_yaml_last_error_message`] then describes the
 * failure (the parse error's rendered `Display` message, including line/column, for
 * `ParseError`).
 *
 * # Safety
 * `source` must be null or point to at least `len` readable bytes. `out_error` must be null or
 * a valid, aligned, writable pointer to a `TptYamlErrorCode`.
 */
struct TptYamlDocument *tpt_yaml_parse(const uint8_t *source,
                                       uintptr_t len,
                                       enum TptYamlErrorCode *out_error);

/**
 * Free a document handle previously returned by [`tpt_yaml_parse`].
 *
 * `doc` may be null, in which case this is a no-op.
 *
 * # Memory-safety contract
 * - Each successful [`tpt_yaml_parse`] result must be freed **exactly once**.
 * - Calling this twice on the same non-null pointer (double-free) is undefined behavior — it is
 *   the caller's responsibility not to do so; this function does not null out or poison the
 *   pointer it's given (a plain C ABI has no way to reach back into the caller's variable to do
 *   that).
 * - Using `doc`, or any node id / borrowed string obtained from it, after this call
 *   (use-after-free) is undefined behavior.
 *
 * # Safety
 * `doc` must be null or a pointer previously returned by [`tpt_yaml_parse`] and not already
 * freed.
 */
void tpt_yaml_document_free(struct TptYamlDocument *doc);

/**
 * Write the document's root node id to `*out_node`.
 *
 * Fails with `IndexOutOfBounds` if the document contains no documents (an empty stream).
 *
 * # Safety
 * `doc` must be null or a live [`tpt_yaml_parse`] result. `out_node` must be null or a valid,
 * aligned, writable pointer to a `TptYamlNodeId` (`u32`).
 */
enum TptYamlErrorCode tpt_yaml_document_root(const struct TptYamlDocument *doc,
                                             TptYamlNodeId *out_node);

/**
 * Write the resolved YAML version as `*out_major`/`*out_minor` (`1`/`1` or `1`/`2`).
 *
 * # Safety
 * `doc` must be null or a live [`tpt_yaml_parse`] result. `out_major`/`out_minor` must each be
 * null or a valid, aligned, writable pointer to a `u32`.
 */
enum TptYamlErrorCode tpt_yaml_document_version(const struct TptYamlDocument *doc,
                                                uint32_t *out_major,
                                                uint32_t *out_minor);

/**
 * Write `node`'s structural kind to `*out_kind`.
 *
 * # Safety
 * `doc` must be null or a live [`tpt_yaml_parse`] result. `out_kind` must be null or a valid,
 * aligned, writable pointer to a `TptYamlNodeKind`.
 */
enum TptYamlErrorCode tpt_yaml_node_kind(const struct TptYamlDocument *doc,
                                         TptYamlNodeId node,
                                         enum TptYamlNodeKind *out_kind);

/**
 * Write the target of an alias node to `*out_node`. Fails with `TypeMismatch` if `node` isn't
 * [`TptYamlNodeKind::Alias`].
 *
 * # Safety
 * See [`tpt_yaml_node_kind`].
 */
enum TptYamlErrorCode tpt_yaml_alias_target(const struct TptYamlDocument *doc,
                                            TptYamlNodeId node,
                                            TptYamlNodeId *out_node);

/**
 * Write `node`'s resolved scalar type tag to `*out_type`. Fails with `TypeMismatch` if `node`
 * isn't a scalar.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`].
 */
enum TptYamlErrorCode tpt_yaml_scalar_type(const struct TptYamlDocument *doc,
                                           TptYamlNodeId node,
                                           enum TptYamlScalarType *out_type);

/**
 * Write a scalar node's boolean value to `*out_value`. Fails with `TypeMismatch` if `node`
 * isn't a `Bool` scalar.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_value` must be null or a valid, aligned, writable pointer to
 * a `bool`.
 */
enum TptYamlErrorCode tpt_yaml_scalar_as_bool(const struct TptYamlDocument *doc,
                                              TptYamlNodeId node,
                                              bool *out_value);

/**
 * Write a scalar node's integer value to `*out_value`. Fails with `TypeMismatch` if `node`
 * isn't an `Int` scalar.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_value` must be null or a valid, aligned, writable pointer to
 * an `i64`.
 */
enum TptYamlErrorCode tpt_yaml_scalar_as_int(const struct TptYamlDocument *doc,
                                             TptYamlNodeId node,
                                             int64_t *out_value);

/**
 * Write a scalar node's float value to `*out_value`. Fails with `TypeMismatch` if `node` isn't
 * a `Float` scalar.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_value` must be null or a valid, aligned, writable pointer to
 * an `f64`.
 */
enum TptYamlErrorCode tpt_yaml_scalar_as_float(const struct TptYamlDocument *doc,
                                               TptYamlNodeId node,
                                               double *out_value);

/**
 * Write a borrowed pointer/length pair for a scalar node's string value (covers both `String`
 * and `Timestamp` scalars, matching [`tpt_yaml_core::ScalarValue::as_str`]) to
 * `*out_ptr`/`*out_len`. Fails with `TypeMismatch` for any other scalar type or non-scalar node.
 *
 * The returned pointer is **not** null-terminated and is borrowed from the document: it is
 * valid only until `doc` is freed via [`tpt_yaml_document_free`], and must not be freed by the
 * caller.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_ptr` must be null or a valid, aligned, writable pointer to a
 * `*const u8`; `out_len` must be null or a valid, aligned, writable pointer to a `usize`.
 */
enum TptYamlErrorCode tpt_yaml_scalar_string(const struct TptYamlDocument *doc,
                                             TptYamlNodeId node,
                                             const char **out_ptr,
                                             uintptr_t *out_len);

/**
 * Write a mapping node's entry count to `*out_len`. Fails with `TypeMismatch` if `node` isn't a
 * mapping.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_len` must be null or a valid, aligned, writable pointer to a
 * `usize`.
 */
enum TptYamlErrorCode tpt_yaml_mapping_len(const struct TptYamlDocument *doc,
                                           TptYamlNodeId node,
                                           uintptr_t *out_len);

/**
 * Write the key node id of a mapping's `index`-th entry to `*out_node`. Fails with
 * `TypeMismatch` if `node` isn't a mapping, or `IndexOutOfBounds` if `index >= ` its length.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`].
 */
enum TptYamlErrorCode tpt_yaml_mapping_key_at(const struct TptYamlDocument *doc,
                                              TptYamlNodeId node,
                                              uintptr_t index,
                                              TptYamlNodeId *out_node);

/**
 * Write the value node id of a mapping's `index`-th entry to `*out_node`. Fails with
 * `TypeMismatch` if `node` isn't a mapping, or `IndexOutOfBounds` if `index >= ` its length.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`].
 */
enum TptYamlErrorCode tpt_yaml_mapping_value_at(const struct TptYamlDocument *doc,
                                                TptYamlNodeId node,
                                                uintptr_t index,
                                                TptYamlNodeId *out_node);

/**
 * Look up a mapping entry by a plain string key (matched against scalar keys' resolved string
 * value — i.e. an unquoted or quoted plain string key, not e.g. an int or nested-collection
 * key), writing the matching entry's value node id to `*out_node`.
 *
 * Fails with `TypeMismatch` if `node` isn't a mapping, or `IndexOutOfBounds` if no entry has a
 * matching string key (reused here as "lookup failed" rather than adding a dedicated
 * not-found code).
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; additionally, `key_ptr` must be null (only if `key_len` is `0`)
 * or point to at least `key_len` readable bytes.
 */
enum TptYamlErrorCode tpt_yaml_mapping_get(const struct TptYamlDocument *doc,
                                           TptYamlNodeId node,
                                           const uint8_t *key_ptr,
                                           uintptr_t key_len,
                                           TptYamlNodeId *out_node);

/**
 * Write a sequence node's item count to `*out_len`. Fails with `TypeMismatch` if `node` isn't a
 * sequence.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`]; `out_len` must be null or a valid, aligned, writable pointer to a
 * `usize`.
 */
enum TptYamlErrorCode tpt_yaml_sequence_len(const struct TptYamlDocument *doc,
                                            TptYamlNodeId node,
                                            uintptr_t *out_len);

/**
 * Write the node id of a sequence's `index`-th item to `*out_node`. Fails with `TypeMismatch`
 * if `node` isn't a sequence, or `IndexOutOfBounds` if `index >= ` its length.
 *
 * # Safety
 * See [`tpt_yaml_node_kind`].
 */
enum TptYamlErrorCode tpt_yaml_sequence_item(const struct TptYamlDocument *doc,
                                             TptYamlNodeId node,
                                             uintptr_t index,
                                             TptYamlNodeId *out_node);

/**
 * Returns a pointer to the current thread's last-error message, or null if none is set (either
 * no error has occurred yet on this thread, or the most recent call succeeded).
 *
 * # Safety / lifetime contract
 *
 * The returned pointer is owned by this crate's internal thread-local storage. It is valid
 * only until the next call into any `tpt_yaml_*` function *on the same thread*, which may
 * overwrite or clear it — copy the string out (e.g. with `strdup`) before making another call
 * if you need it to outlive that. Never call `free`/`tpt_yaml_string_free` on it.
 */
const char *tpt_yaml_last_error_message(void);

#endif  /* TPT_YAML_H */
