[package]
name = "tpt-yaml-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "A command-line tool for parsing, formatting, validating, converting, and diffing YAML files."
keywords = ["yaml", "cli", "formatter", "linter", "diff"]
categories = ["command-line-utilities"]

[[bin]]
name = "tpt-yaml"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
tpt-yaml-core = { path = "../tpt-yaml-core", version = "0.1.0" }
tpt-yaml-edit = { path = "../tpt-yaml-edit", version = "0.1.0" }
tpt-yaml-schema = { path = "../tpt-yaml-schema", version = "0.1.0" }
tpt-yaml-serde = { path = "../tpt-yaml-serde", version = "0.1.0" }
